version: '3.8'

services:
  backend:
    build:
      context: ./Backend/ms-cartas
    ports:
      - "8080:8080"
    networks:
      - yugi-network

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80" # El frontend estará disponible en http://localhost:3000
    depends_on:
      - backend
    networks:
      - yugi-network

networks:
  yugi-network:
    driver: bridge